import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';const html=await readFile(new URL('../web/index.html',import.meta.url),'utf8');const css=await readFile(new URL('../web/assets/styles.css',import.meta.url),'utf8');const siteJs=await readFile(new URL('../web/assets/app.js',import.meta.url),'utf8');const adminHtml=await readFile(new URL('../web/admin/index.html',import.meta.url),'utf8');const serverJs=await readFile(new URL('../src/app.js',import.meta.url),'utf8');const reviews=JSON.parse(await readFile(new URL('../web/data/reviews.json',import.meta.url),'utf8'));const defaults=JSON.parse(await readFile(new URL('../src/reviews-default.json',import.meta.url),'utf8'));const section=html.slice(html.indexOf('id="reviews"'),html.indexOf('</section>',html.indexOf('id="reviews"')));
test('reviews section contains real client letters',()=>{for(const author of['Илона Рябова','Иван и Наталия','Ангелина Петрова'])assert.ok(section.includes(author),`Отзыв «${author}» отсутствует в разделе`);assert.equal((section.match(/class="rev"/g)||[]).length,3);assert.ok(!html.includes('Семья Ковалёвых'),'Демонстрационный отзыв должен быть удалён')});
test('every review can be expanded without javascript',()=>{assert.equal((section.match(/<details class="rev-more">/g)||[]).length,3);assert.equal((section.match(/<summary>/g)||[]).length,3);assert.equal((section.match(/class="rev-open"/g)||[]).length,3);assert.equal((section.match(/class="rev-close"/g)||[]).length,3)});
test('reviews grid styles are shipped and cache-busted',()=>{for(const rule of['.reviews-grid','.rev-lead','.rev-more>summary','.rev-by','.review-note'])assert.ok(css.includes(rule),`Нет правила ${rule}`);assert.match(html,/styles\.css\?v=20260731-3/);assert.match(html,/app\.js\?v=20260731-3/)});
test('reviews.json mirrors the static fallback markup',()=>{assert.equal(reviews.length,3);for(const item of reviews){assert.ok(item.author,'У отзыва нет автора');assert.ok(item.lead,'У отзыва нет начала письма');assert.ok(Array.isArray(item.body),'body должен быть массивом абзацев');assert.ok(section.includes(item.author),`Автор ${item.author} расходится со статичной вёрсткой`)}assert.equal(reviews[1].psText.includes('тревожная мать'),true)});
test('public page renders reviews from json over the static fallback',()=>{assert.match(siteJs,/enhanceReviews\(\)/);assert.match(siteJs,/\/data\/reviews\.json/);assert.match(siteJs,/#reviews \.reviews-grid/);assert.ok(!/innerHTML/.test(siteJs.slice(siteJs.indexOf('function reviewCard'),siteJs.indexOf('enhanceReviews();'))),'Отзывы должны рендериться через textContent, без innerHTML')});
test('admin panel exposes reviews crud',()=>{assert.ok(adminHtml.includes('data-tab="reviews"'),'Нет вкладки «Отзывы»');assert.ok(adminHtml.includes('id="reviews-tab"'));for(const control of['add-review','save-reviews','reviews-list','reviews-form'])assert.ok(adminHtml.includes(`id="${control}"`),`Нет элемента ${control}`);assert.ok(adminHtml.includes('data-remove='),'Нет удаления отзыва');assert.ok(adminHtml.includes("data-move=\"up\""),'Нет перемещения отзыва');assert.ok(adminHtml.includes('/api/admin/reviews'),'Админка не ходит в API отзывов')});
test('server exposes protected reviews endpoints',()=>{assert.ok(serverJs.includes("req.url === '/api/admin/reviews'"),'Нет роутов /api/admin/reviews');assert.ok(serverJs.includes('validateAdminReviews'),'Нет валидации отзывов');assert.ok(serverJs.includes("data/reviews.json"),'Отзывы не пишутся в data/reviews.json')});
test('reviews survive a pre-existing docker volume',()=>{assert.deepEqual(defaults,reviews,'Дефолты в образе должны совпадать с данными тома');assert.ok(serverJs.includes("new URL('./reviews-default.json', import.meta.url)"),'Нет фолбэка на дефолты образа, когда файл в томе отсутствует');assert.ok(!adminHtml.includes("api('/api/admin/reviews')]"),'Загрузка отзывов не должна ронять всю админ-панель')});
