import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { buildServer } from '../src/app.js';
function fixture() { const calls = []; const server = buildServer({ config: { telegram: { webhookSecret: 't' }, max: { webhookSecret: 'm' }, vk: { groupId: '1', secret: 'v', confirmationCode: 'c' } }, store: {}, vk: {}, botCore: {}, platforms: {}, uon: { async createQualifiedLead(tourist) { calls.push(tourist); return { id: 'SITE-42' }; } }, notifier: { async notify() {} }, logger: { warn() {}, error() {} } }); return { server, calls }; }
async function withServer(run) { const { server, calls } = fixture(); server.listen(0, '127.0.0.1'); await once(server, 'listening'); try { await run(`http://127.0.0.1:${server.address().port}`, calls); } finally { server.close(); await once(server, 'close'); } }
test('serves the travel agency website', async () => withServer(async base => { const response = await fetch(base + '/'); const html = await response.text(); assert.equal(response.status, 200); assert.match(html, /Сбежим на море/); assert.match(response.headers.get('content-type'), /text\/html/); }));
test('rejects site lead without explicit consents', async () => withServer(async base => { const response = await fetch(base + '/api/site/leads', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Ирина', phone: '+7 999 123-45-67' }) }); assert.equal(response.status, 422); }));
test('creates U-ON lead from a valid site form', async () => withServer(async (base, calls) => { const response = await fetch(base + '/api/site/leads', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Ирина', phone: '+7 999 123-45-67', destination: 'Мальдивы', personalConsent: true, marketingConsent: true }) }); assert.equal(response.status, 201); assert.deepEqual(await response.json(), { ok: true, leadId: 'SITE-42' }); assert.equal(calls[0].platform, 'website'); assert.equal(calls[0].destination, 'Мальдивы'); }));
