import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { buildServer } from '../src/app.js';
function fixture() { const calls = []; const server = buildServer({ config: { telegram: { webhookSecret: 't' }, max: { webhookSecret: 'm' }, vk: { groupId: '1', secret: 'v', confirmationCode: 'c' } }, store: {}, vk: {}, botCore: {}, platforms: {}, uon: { async createQualifiedLead(tourist) { calls.push(tourist); return { id: 'SITE-42' }; } }, notifier: { async notify() {} }, logger: { warn() {}, error() {} } }); return { server, calls }; }
async function withServer(run) { const { server, calls } = fixture(); server.listen(0, '127.0.0.1'); await once(server, 'listening'); try { await run(`http://127.0.0.1:${server.address().port}`, calls); } finally { server.close(); await once(server, 'close'); } }
const valid = { name: 'Ирина', phone: '+7 999 123-45-67', destination: 'Мальдивы', personalConsent: true, marketingConsent: true };
test('serves website with security headers', async () => withServer(async base => { const response = await fetch(base + '/'); const html = await response.text(); assert.equal(response.status, 200); assert.match(html, /Сбежим на море/); assert.match(response.headers.get('content-type'), /text\/html/); assert.match(response.headers.get('content-security-policy'), /default-src/); assert.equal(response.headers.get('x-content-type-options'), 'nosniff'); }));
test('requires JSON for site leads', async () => withServer(async base => { const response = await fetch(base + '/api/site/leads', { method: 'POST', body: 'name=Ирина' }); assert.equal(response.status, 415); }));
test('rejects site lead without explicit consents', async () => withServer(async base => { const response = await fetch(base + '/api/site/leads', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Ирина', phone: '+7 999 123-45-67' }) }); assert.equal(response.status, 422); }));
test('creates U-ON lead from a valid site form', async () => withServer(async (base, calls) => { const response = await fetch(base + '/api/site/leads', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(valid) }); assert.equal(response.status, 201); assert.deepEqual(await response.json(), { ok: true, leadId: 'SITE-42' }); assert.equal(calls[0].platform, 'website'); assert.equal(calls[0].destination, 'Мальдивы'); }));
test('rejects invalid email before creating a lead', async () => withServer(async (base, calls) => { const response = await fetch(base + '/api/site/leads', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...valid, email: 'wrong' }) }); assert.equal(response.status, 422); assert.equal(calls.length, 0); }));
test('rate limits repeated website submissions', async () => withServer(async base => { const options = { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(valid) }; for (let i = 0; i < 5; i += 1) assert.equal((await fetch(base + '/api/site/leads', options)).status, 201); const blocked = await fetch(base + '/api/site/leads', options); assert.equal(blocked.status, 429); assert.equal(blocked.headers.get('retry-after'), '600'); }));
