import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { setTimeout as sleep } from 'node:timers/promises';
import { funnelRows } from './bot-funnel.js';

const EMPTY={employees:[],clientMeta:{},segments:[],campaigns:[]};
const ROLES={head:['employees','clients','segments','broadcasts'],specialist:['clients','segments','broadcasts'],manager:['clients']};
const json=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(payload))};
async function readJson(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>300_000)throw new Error('Payload too large');chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}
const hashPassword=password=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`};
const verifyPassword=(password,encoded)=>{try{const[salt,hash]=encoded.split(':');const actual=scryptSync(password,salt,64),expected=Buffer.from(hash,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected)}catch{return false}};
const clean=(value,max=120)=>String(value||'').trim().slice(0,max);
const keyOf=(platform,userId)=>`${platform}:${userId}`;

export class BotAdminStore{
 #file;#data=structuredClone(EMPTY);#queue=Promise.resolve();
 constructor(file){this.#file=file}
 async init(){await mkdir(dirname(this.#file),{recursive:true});try{this.#data={...structuredClone(EMPTY),...JSON.parse(await readFile(this.#file,'utf8'))}}catch(error){if(error.code!=='ENOENT')throw error;await this.#persist()}}
 listEmployees(){return this.#data.employees.map(({passwordHash,...item})=>item)}
 authenticate(username,password){const item=this.#data.employees.find(e=>e.active&&e.username===username);return item&&verifyPassword(password,item.passwordHash)?{id:item.id,username:item.username,name:item.name,role:item.role,permissions:ROLES[item.role]||[]}:null}
 async saveEmployee(input){const username=clean(input.username,60).toLowerCase(),name=clean(input.name,120),role=ROLES[input.role]?input.role:null,password=String(input.password||'');if(!username||!name||!role)throw new Error('Заполните имя, логин и роль.');if(!/^[a-z0-9._-]{3,60}$/.test(username))throw new Error('Логин: латиница, цифры, точка, дефис или подчёркивание.');let item=input.id?this.#data.employees.find(e=>e.id===input.id):null;if(!item&&this.#data.employees.some(e=>e.username===username))throw new Error('Такой логин уже существует.');if(!item&&password.length<10)throw new Error('Пароль должен содержать минимум 10 символов.');if(item){item.username=username;item.name=name;item.role=role;item.active=input.active!==false;if(password)item.passwordHash=hashPassword(password);item.updatedAt=new Date().toISOString()}else{item={id:randomUUID(),username,name,role,active:true,passwordHash:hashPassword(password),createdAt:new Date().toISOString()};this.#data.employees.push(item)}await this.#persistQueued();return this.listEmployees().find(e=>e.id===item.id)}
 async deleteEmployee(id){const item=this.#data.employees.find(e=>e.id===id);if(!item)return false;item.active=false;item.updatedAt=new Date().toISOString();await this.#persistQueued();return true}
 clientMeta(key){return structuredClone(this.#data.clientMeta[key]||{})}
 async updateClient(key,input){const current=this.#data.clientMeta[key]||{};this.#data.clientMeta[key]={...current,name:clean(input.name,120),interests:[...new Set((input.interests||[]).map(v=>clean(v,80)).filter(Boolean))].slice(0,20),tags:[...new Set((input.tags||[]).map(v=>clean(v,60)).filter(Boolean))].slice(0,30),notes:clean(input.notes,1000),updatedAt:new Date().toISOString()};await this.#persistQueued();return structuredClone(this.#data.clientMeta[key])}
 listSegments(){return structuredClone(this.#data.segments)}
 async saveSegment(input){const name=clean(input.name,120);if(!name)throw new Error('Укажите название сегмента.');const filters={country:clean(input.filters?.country,120),budget:clean(input.filters?.budget,120),interest:clean(input.filters?.interest,80),tag:clean(input.filters?.tag,60),platform:['telegram','max'].includes(input.filters?.platform)?input.filters.platform:''};let item=input.id?this.#data.segments.find(s=>s.id===input.id):null;if(item){Object.assign(item,{name,filters,updatedAt:new Date().toISOString()})}else{item={id:randomUUID(),name,filters,createdAt:new Date().toISOString()};this.#data.segments.push(item)}await this.#persistQueued();return structuredClone(item)}
 async deleteSegment(id){const before=this.#data.segments.length;this.#data.segments=this.#data.segments.filter(s=>s.id!==id);if(this.#data.segments.length===before)return false;await this.#persistQueued();return true}
 listCampaigns(){return structuredClone(this.#data.campaigns.slice(-100).reverse())}
 async addCampaign(item){this.#data.campaigns.push(item);this.#data.campaigns=this.#data.campaigns.slice(-500);await this.#persistQueued();return structuredClone(item)}
 #persistQueued(){this.#queue=this.#queue.catch(()=>{}).then(()=>this.#persist());return this.#queue}
 async #persist(){const temp=`${this.#file}.tmp`;await writeFile(temp,JSON.stringify(this.#data,null,2),{mode:0o600});await rename(temp,this.#file)}
}

export class BotAdminService{
 constructor({file,store,platforms,masterCredential,logger=console}){this.data=new BotAdminStore(file);Object.assign(this,{store,platforms,masterCredential,logger})}
 async init(){await this.data.init()}
 auth(req){const credential=String(req.headers['x-admin-password']||'');if(credential&&credential===this.masterCredential)return{username:'master',name:'Руководитель',role:'head',permissions:ROLES.head};const split=credential.indexOf(':');return split>0?this.data.authenticate(credential.slice(0,split),credential.slice(split+1)):null}
 clients(){const subscriptions=this.store.listSubscriptions?.()||[],map=new Map();for(const sub of subscriptions){const key=keyOf(sub.platform,sub.userId),old=map.get(key),params=sub.params||{};map.set(key,{key,platform:sub.platform,userId:String(sub.userId),country:clean(params.destination,120),budget:clean(params.budget,120),group:clean(params.group,120),dates:clean(params.dates,120),active:true,createdAt:sub.createdAt,...old,...this.data.clientMeta(key)})}return[...map.values()]}
 filterClients(filters={}){const subscribed=String(filters.subscribed||'');return this.clients().filter(c=>(!filters.platform||c.platform===filters.platform)&&(!filters.country||c.country.toLowerCase().includes(filters.country.toLowerCase()))&&(!filters.budget||c.budget.toLowerCase().includes(filters.budget.toLowerCase()))&&(!filters.interest||(c.interests||[]).some(v=>v.toLowerCase().includes(filters.interest.toLowerCase())))&&(!filters.tag||(c.tags||[]).some(v=>v.toLowerCase()===filters.tag.toLowerCase()))&&(!subscribed||(subscribed==='1'?c.active!==false:c.active===false)))}
 // Рассылки уходят только тем, кто дал согласие на рекламные сообщения
 // и не отписался: остальные контакты доступны только для просмотра.
 broadcastRecipients(filters={}){return this.filterClients(filters).filter(c=>c.active!==false)}
 async broadcast({message,segmentId,linkText,linkUrl},actor){message=clean(message,3500);if(!message)throw new Error('Введите текст сообщения.');if(linkUrl&&!/^https:\/\//i.test(linkUrl))throw new Error('Ссылка должна начинаться с https://');const segment=segmentId?this.data.listSegments().find(s=>s.id===segmentId):null;if(segmentId&&!segment)throw new Error('Сегмент не найден.');const recipients=this.broadcastRecipients(segment?.filters||{});if(!recipients.length)throw new Error('В выбранном сегменте нет активных подписчиков рассылки.');const output={text:message,buttons:linkUrl?[[{text:clean(linkText,60)||'Подробнее',url:linkUrl}]]:[]};let sent=0,failed=0;const errors=[];for(const client of recipients){try{const platform=this.platforms[client.platform];if(!platform)throw new Error('Платформа не подключена');await platform.send(client.userId,output);sent++}catch(error){failed++;errors.push({key:client.key,error:error.message.slice(0,200)})}await sleep(50)}const campaign={id:randomUUID(),message,segmentId:segment?.id||null,segmentName:segment?.name||'Все активные подписчики',linkText:clean(linkText,60),linkUrl:clean(linkUrl,500),recipients:recipients.length,sent,failed,errors:errors.slice(0,30),createdBy:actor.username,createdAt:new Date().toISOString()};await this.data.addCampaign(campaign);return campaign}
 async handle(req,res){const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api/bot-admin/'))return false;const actor=this.auth(req);if(!actor){json(res,401,{error:'Неверный логин или пароль.'});return true}const need=permission=>{if(!actor.permissions.includes(permission)){json(res,403,{error:'Недостаточно прав.'});return false}return true};try{
  if(req.method==='GET'&&url.pathname==='/api/bot-admin/me'){json(res,200,{ok:true,user:actor});return true}
  if(url.pathname==='/api/bot-admin/employees'){if(!need('employees'))return true;if(req.method==='GET'){json(res,200,{ok:true,employees:this.data.listEmployees()});return true}if(req.method==='POST'){json(res,200,{ok:true,employee:await this.data.saveEmployee(await readJson(req))});return true}}
  if(req.method==='DELETE'&&url.pathname.startsWith('/api/bot-admin/employees/')){if(!need('employees'))return true;json(res,200,{ok:await this.data.deleteEmployee(url.pathname.split('/').pop())});return true}
  if(url.pathname==='/api/bot-admin/clients'){if(!need('clients'))return true;if(req.method==='GET'){const filters=Object.fromEntries(url.searchParams);json(res,200,{ok:true,clients:this.filterClients(filters),subscribers:this.broadcastRecipients(filters).length});return true}if(req.method==='POST'){const body=await readJson(req);if(!/^\w+:.+/.test(body.key||''))throw new Error('Некорректный клиент.');json(res,200,{ok:true,client:await this.data.updateClient(body.key,body)});return true}}
  if(req.method==='GET'&&url.pathname==='/api/bot-admin/funnel'){if(!need('clients'))return true;const rows=funnelRows(this.store.listBotUsers?.()||[]);const only=url.searchParams.get('state')||'';const filtered=only==='abandoned'?rows.filter(r=>r.abandoned):only==='completed'?rows.filter(r=>r.completedAt):rows;json(res,200,{ok:true,rows:filtered,total:rows.length,abandoned:rows.filter(r=>r.abandoned).length,completed:rows.filter(r=>r.completedAt).length});return true}
  if(url.pathname==='/api/bot-admin/segments'){if(!need('segments'))return true;if(req.method==='GET'){json(res,200,{ok:true,segments:this.data.listSegments()});return true}if(req.method==='POST'){json(res,200,{ok:true,segment:await this.data.saveSegment(await readJson(req))});return true}}
  if(req.method==='DELETE'&&url.pathname.startsWith('/api/bot-admin/segments/')){if(!need('segments'))return true;json(res,200,{ok:await this.data.deleteSegment(url.pathname.split('/').pop())});return true}
  if(req.method==='GET'&&url.pathname==='/api/bot-admin/campaigns'){if(!need('broadcasts'))return true;json(res,200,{ok:true,campaigns:this.data.listCampaigns()});return true}
  if(req.method==='POST'&&url.pathname==='/api/bot-admin/broadcasts'){if(!need('broadcasts'))return true;json(res,200,{ok:true,campaign:await this.broadcast(await readJson(req),actor)});return true}
  json(res,404,{error:'Метод не найден.'});return true
 }catch(error){this.logger.error('Bot admin request failed',{url:req.url,error:error.message});json(res,422,{error:error.message});return true}}
}
