import { setTimeout as sleep } from 'node:timers/promises';
async function fetchJson(url, options = {}, timeoutMs = 10000) { const response = await fetch(url, { ...options, signal: AbortSignal.timeout(timeoutMs) }); const text = await response.text(); let data; try { data = text ? JSON.parse(text) : {}; } catch { data = { raw: text }; } if (!response.ok) throw new Error(`HTTP ${response.status}: ${JSON.stringify(data)}`); return data; }

export class UonClient {
  constructor(config) { this.config = config; }
  async createLead(tourist) { return this.#create({ source: this.config.source, u_name: tourist.name, u_phone: tourist.phone, u_email: tourist.email, [this.config.commentField]: [`Направление: ${tourist.destination}`, `Даты: ${tourist.dates}`, `Туристы: ${tourist.travelers}`, `Бюджет: ${tourist.budget}`, `VK ID: ${tourist.vkUserId}`].join('\n') }); }
  async createQualifiedLead(t) { return this.#create({ source: `${this.config.source} — ${t.platform}`, u_name: t.name, u_phone: t.phone, u_email: t.email, [this.config.commentField]: [`Квалифицированное обращение`, `Направление: ${t.destination}`, `Даты: ${t.dates}`, `Бюджет: ${t.budget}`, `Состав: ${t.group}`, `Пожелания: ${t.wishes}`, `Пользователь: ${t.platform}:${t.messengerUserId}`].join('\n') }); }
  async createBookingLead(t) { const o = t.selectedTour; return this.#create({ source: `${this.config.source} — намерение бронирования`, u_name: t.name, u_phone: t.phone, [this.config.commentField]: [`Выбранный тур: ${o.hotel}`, `ID предложения: ${o.id}`, `Направление: ${o.destination}`, `Даты: ${o.dates}`, `Цена: ${o.price}`, `Мессенджер: ${t.messenger}`, `Ссылка: ${o.siteUrl}`].join('\n') }); }
  async #create(fields) { const body = new URLSearchParams(Object.fromEntries(Object.entries(fields).filter(([, v]) => v != null))); const url = 'https://api.u-on.ru/' + encodeURIComponent(this.config.apiKey) + '/lead/create.json'; let lastError; for (let attempt = 0; attempt <= this.config.retries; attempt += 1) { try { const data = await fetchJson(url, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body }, this.config.timeoutMs); const scalarResult = ['string', 'number'].includes(typeof data.result) ? data.result : undefined; const id = data.id ?? data.lead_id ?? data.result?.id ?? scalarResult; if (!id) throw new Error(`U-ON response has no lead id: ${JSON.stringify(data)}`); return { id: String(id), raw: data }; } catch (e) { lastError = e; if (attempt < this.config.retries) await sleep(300 * 2 ** attempt); } } throw lastError; }
}
export class VkClient { constructor(config) { this.config = config; } async sendMessage(peerId, message) { const body = new URLSearchParams({ access_token: this.config.token, v: this.config.apiVersion, peer_id: String(peerId), random_id: String(Math.floor(Math.random() * 2147483647)), message }); const data = await fetchJson('https://api.vk.com/method/messages.send', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body }); if (data.error) throw new Error(`VK API: ${JSON.stringify(data.error)}`); return data.response; } }
export class Notifier { constructor(email, telegram) { this.email = email; this.telegram = telegram; } format(id, t) { return [`Новое обращение №${id}`, `Имя: ${t.name}`, `Телефон: ${t.phone}`, `Email: ${t.email}`, `Направление: ${t.destination}`, `Даты: ${t.dates}`, `Туристы: ${t.travelers}`, `Бюджет: ${t.budget}`, `Источник: ${t.vkUserId}`].join('\n'); } async notify(id, t) { const text = this.format(id, t); const email = fetchJson('https://api.resend.com/emails', { method: 'POST', headers: { authorization: `Bearer ${this.email.apiKey}`, 'content-type': 'application/json' }, body: JSON.stringify({ from: this.email.from, to: this.email.to, subject: `Новое обращение U-ON №${id}`, text }) }); const telegram = fetchJson('https://api.telegram.org/bot' + this.telegram.botToken + '/sendMessage', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ chat_id: this.telegram.chatId, text }) }); const result = await Promise.allSettled([email, telegram]); return { email: result[0].status, telegram: result[1].status }; } }
