async function fetchJson(url, options) { const response = await fetch(url, { ...options, signal: AbortSignal.timeout(10000) }); const data = await response.json(); if (!response.ok || data.ok === false) throw new Error(`Platform API ${response.status}: ${JSON.stringify(data)}`); return data; }
export class TelegramClient {
  constructor(config) { this.config = config; }
  async send(userId, output) { const inline_keyboard = (output.buttons || []).map((row) => row.map((b) => b.url ? { text: b.text, url: b.url } : { text: b.text, callback_data: b.callback })); const url = 'https://api.telegram.org/bot' + this.config.token + '/sendMessage'; return fetchJson(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ chat_id: userId, text: output.text, reply_markup: inline_keyboard.length ? { inline_keyboard } : undefined }) }); }
  async ack(callbackId) { if (!callbackId) return; const url = 'https://api.telegram.org/bot' + this.config.token + '/answerCallbackQuery'; await fetchJson(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ callback_query_id: callbackId }) }); }
  parse(u) { if (u.callback_query) return { eventId: `tg:cb:${u.callback_query.id}`, ackId: u.callback_query.id, userId: String(u.callback_query.from.id), input: { callback: u.callback_query.data } }; const m = u.message; return m?.from?.id ? { eventId: `tg:msg:${m.message_id}:${m.chat.id}`, userId: String(m.from.id), input: { text: m.text || '' } } : null; }
}
export class MaxClient {
  constructor(config) { this.config = config; }
  async send(userId, output) { const buttons = (output.buttons || []).map((row) => row.map((b) => b.url ? { type: 'link', text: b.text, url: b.url } : { type: 'callback', text: b.text, payload: b.callback })); const body = { text: output.text, attachments: buttons.length ? [{ type: 'inline_keyboard', payload: { buttons } }] : undefined }; return fetchJson(`${this.config.apiUrl}/messages?user_id=${encodeURIComponent(userId)}`, { method: 'POST', headers: { Authorization: this.config.token, 'content-type': 'application/json' }, body: JSON.stringify(body) }); }
  parse(u) { if (u.update_type === 'message_callback') { const c = u.callback || u.message_callback || {}; const id = c.user?.user_id ?? c.user_id ?? u.user?.user_id; const payload = c.payload ?? c.callback_data; const callbackId = c.callback_id ?? `${u.timestamp}:${id}:${payload}`; return id && payload ? { eventId: `max:cb:${callbackId}`, userId: String(id), input: { callback: payload } } : null; } if (u.update_type === 'bot_started') { const id = u.user?.user_id; return id ? { eventId: `max:start:${u.timestamp}:${id}`, userId: String(id), input: { text: '/start' } } : null; } if (u.update_type !== 'message_created') return null; const m = u.message || {}; const id = m.sender?.user_id ?? m.user?.user_id ?? u.user?.user_id; return id ? { eventId: `max:msg:${m.body?.mid || m.mid || u.timestamp}:${id}`, userId: String(id), input: { text: m.body?.text || m.text || '' } } : null; }
}
