import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { randomUUID } from 'node:crypto';
const EMPTY={sessions:{},botSessions:{},botUsers:{},processedEvents:{},subscriptions:[],offers:{},consentEvidence:[],legalDocuments:{}};
export class JsonStore{
 #file;#data=structuredClone(EMPTY);#queue=Promise.resolve();constructor(file){this.#file=file}
 async init(){await mkdir(dirname(this.#file),{recursive:true});try{this.#data={...structuredClone(EMPTY),...JSON.parse(await readFile(this.#file,'utf8'))};if(!this.#data.botUsers)this.#data.botUsers={};if(!Array.isArray(this.#data.consentEvidence))this.#data.consentEvidence=[];if(!this.#data.legalDocuments||typeof this.#data.legalDocuments!=='object')this.#data.legalDocuments={}}catch(e){if(e.code!=='ENOENT')throw e;await this.#persist()}}
 getSession(id){return structuredClone(this.#data.sessions[id]||null)}async saveSession(id,value){this.#data.sessions[id]=structuredClone(value);await this.#persistQueued()}
 getBotSession(id){return structuredClone(this.#data.botSessions[id]||null)}async saveBotSession(id,value){this.#data.botSessions[id]=structuredClone(value);const[platform,...parts]=id.split(':');await this.touchBotUser(platform,parts.join(':'),false);await this.#persistQueued()}async clearBotSession(id){delete this.#data.botSessions[id];await this.#persistQueued()}
 async touchBotUser(platform,userId,persist=true){if(!platform||!userId)return;const key=`${platform}:${userId}`,old=this.#data.botUsers[key]||{};this.#data.botUsers[key]={...old,key,platform,userId:String(userId),firstSeenAt:old.firstSeenAt||new Date().toISOString(),lastSeenAt:new Date().toISOString()};if(persist)await this.#persistQueued()}
 async saveBotUserProfile(platform,userId,profile={}){if(!platform||!userId)return;await this.touchBotUser(platform,userId,false);const key=`${platform}:${userId}`,old=this.#data.botUsers[key]||{},prev=old.profile||{},cut=(a,b)=>String(a==null||a===''?(b==null?'':b):a).slice(0,160);this.#data.botUsers[key]={...old,profile:{destination:cut(profile.destination,prev.destination),dates:cut(profile.dates,prev.dates),group:cut(profile.group,prev.group),budget:cut(profile.budget,prev.budget),departureCity:cut(profile.departureCity,prev.departureCity),lastLeadId:cut(profile.lastLeadId,prev.lastLeadId),lastLeadAt:profile.lastLeadId?new Date().toISOString():(prev.lastLeadAt||null)}};await this.#persistQueued()}
 async logBotEvent(platform,userId,event={}){if(!platform||!userId)return;await this.touchBotUser(platform,userId,false);const key=`${platform}:${userId}`,user=this.#data.botUsers[key],cut=(v,n)=>String(v==null?'':v).slice(0,n),step=cut(event.step,40),flow=cut(event.flow,24),now=new Date().toISOString();const trail=Array.isArray(user.trail)?user.trail:[];trail.push({at:now,flow,step,action:cut(event.action,60)});user.trail=trail.slice(-40);const funnel=user.funnel||{};user.funnel={...funnel,flow:flow||funnel.flow||'',step:step||funnel.step||'',startedAt:funnel.startedAt||now,updatedAt:now,completedAt:funnel.completedAt||null,leadId:funnel.leadId||null,remindedAt:funnel.remindedAt||null,remindersSent:funnel.remindersSent||0,remindersOff:funnel.remindersOff||false};await this.#persistQueued()}
 async setBotFunnelStep(platform,userId,{flow='',step=''}={}){if(!platform||!userId)return;const key=`${platform}:${userId}`,user=this.#data.botUsers[key];if(!user||!user.funnel||user.funnel.completedAt)return;user.funnel={...user.funnel,flow:String(flow||user.funnel.flow||'').slice(0,24),step:String(step||user.funnel.step||'').slice(0,40),updatedAt:new Date().toISOString()};await this.#persistQueued()}
 async completeBotFunnel(platform,userId,{leadId=null,kind=''}={}){if(!platform||!userId)return;await this.touchBotUser(platform,userId,false);const key=`${platform}:${userId}`,user=this.#data.botUsers[key],funnel=user.funnel||{},now=new Date().toISOString();user.funnel={...funnel,step:String(kind||'completed').slice(0,40),startedAt:funnel.startedAt||now,updatedAt:now,completedAt:now,leadId:leadId==null?funnel.leadId||null:String(leadId),remindedAt:funnel.remindedAt||null,remindersSent:funnel.remindersSent||0,remindersOff:funnel.remindersOff||false};await this.#persistQueued()}
 async markBotReminder(platform,userId,{off=false}={}){if(!platform||!userId)return;const key=`${platform}:${userId}`,user=this.#data.botUsers[key];if(!user)return;const funnel=user.funnel||{};user.funnel={...funnel,remindedAt:new Date().toISOString(),remindersSent:(funnel.remindersSent||0)+(off?0:1),remindersOff:off||funnel.remindersOff||false};await this.#persistQueued()}
 listBotUsers(){return structuredClone(Object.values(this.#data.botUsers))}
 isProcessed(id){return this.#data.processedEvents[id]?.status==='done'||typeof this.#data.processedEvents[id]==='number'}async claimEvent(id){const current=this.#data.processedEvents[id],timestamp=typeof current==='number'?current:current?.at;if(current&&(current.status==='done'||typeof current==='number'))return false;if(current?.status==='processing'&&Date.now()-timestamp<300000)return false;this.#data.processedEvents[id]={status:'processing',at:Date.now()};await this.#persistQueued();return true}async markProcessed(id){this.#data.processedEvents[id]={status:'done',at:Date.now()};const cutoff=Date.now()-604800000;for(const[key,value]of Object.entries(this.#data.processedEvents)){const timestamp=typeof value==='number'?value:value?.at;if(!timestamp||timestamp<cutoff)delete this.#data.processedEvents[key]}await this.#persistQueued()}async releaseEvent(id){if(this.#data.processedEvents[id]?.status==='processing'){delete this.#data.processedEvents[id];await this.#persistQueued()}}
 async addSubscription({platform,userId,params,consent}){await this.touchBotUser(platform,userId,false);const existing=this.#data.subscriptions.find(s=>s.platform===platform&&String(s.userId)===String(userId)&&JSON.stringify(s.params)===JSON.stringify(params));if(existing){existing.active=true;existing.consent=structuredClone(consent||existing.consent||null);existing.updatedAt=Date.now();await this.#persistQueued();return structuredClone(existing)}const item={id:randomUUID(),platform,userId:String(userId),params:structuredClone(params),consent:structuredClone(consent||null),active:true,sentOfferIds:[],createdAt:Date.now()};this.#data.subscriptions.push(item);await this.#persistQueued();return structuredClone(item)}
 async deactivateSubscriptions(platform,userId){let count=0;for(const item of this.#data.subscriptions)if(item.platform===platform&&String(item.userId)===String(userId)&&item.active){item.active=false;item.stoppedAt=Date.now();count++}if(count)await this.#persistQueued();return count}
 listSubscriptions(){return structuredClone(this.#data.subscriptions.filter(s=>s.active))}async markSubscriptionSent(id,offerIds){const item=this.#data.subscriptions.find(s=>s.id===id);if(item){item.sentOfferIds=[...new Set([...(item.sentOfferIds||[]),...offerIds])].slice(-100);item.lastRunAt=Date.now();await this.#persistQueued()}}
 async saveOffer(offer){this.#data.offers[offer.id]={...structuredClone(offer),savedAt:Date.now()};await this.#persistQueued()}getOffer(id){return structuredClone(this.#data.offers[id]||null)}
 async saveConsentEvidence(record){const item={evidenceId:record.evidenceId||randomUUID(),revokedAt:null,revocationReason:null,...structuredClone(record)};this.#data.consentEvidence.push(item);await this.#persistQueued();return structuredClone(item)}listConsentEvidence({uonLeadId,evidenceId}={}){return structuredClone(this.#data.consentEvidence.filter(item=>(!uonLeadId||item.uonLeadId===String(uonLeadId))&&(!evidenceId||item.evidenceId===String(evidenceId))))}async revokeConsentEvidence({uonLeadId,evidenceId,reason,revokedAt=new Date().toISOString()}){const item=this.#data.consentEvidence.find(entry=>(evidenceId&&entry.evidenceId===String(evidenceId))||(uonLeadId&&entry.uonLeadId===String(uonLeadId)));if(!item)return null;item.revokedAt=revokedAt;item.revocationReason=String(reason||'Отзыв согласия субъектом персональных данных').slice(0,500);await this.#persistQueued();return structuredClone(item)}
 getLegalDocument(slug){return this.#data.legalDocuments[slug]?structuredClone(this.#data.legalDocuments[slug]):null}listSavedLegalDocuments(){return structuredClone(this.#data.legalDocuments)}async saveLegalDocument({slug,title,version,contentHtml,updatedAt=new Date().toISOString()}){const current=this.#data.legalDocuments[slug],history=current?[{title:current.title,version:current.version,contentHtml:current.contentHtml,updatedAt:current.updatedAt},...(current.history||[])].slice(0,20):[];const item={title,version,contentHtml,updatedAt,history};this.#data.legalDocuments[slug]=item;await this.#persistQueued();return structuredClone(item)}
 #persistQueued(){this.#queue=this.#queue.catch(()=>{}).then(()=>this.#persist());return this.#queue}async #persist(){const temp=`${this.#file}.tmp`;await writeFile(temp,JSON.stringify(this.#data,null,2),{mode:0o600});await rename(temp,this.#file)}
}
